name: 'Setup Rust'
description: 'Setup Rust by rustup'

inputs:
  channel:
    description: 'Rust release channel[stable|beta|nightly]'
    default: stable
    required: false
  target:
    description: 'Rust build target'
    default: ''
    required: false

outputs:
  version:
    description: "`rustc --version` result"
    value: ${{ steps.set_output.outputs.version }}

runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      shell: bash
      run: |
        rustup update --no-self-update ${{ inputs.channel }}
        rustup default ${{ inputs.channel }}
    - name: Echo rust version
      shell: bash
      run: |
        rustc --version
    - if: ${{ inputs.target != '' }}
      name: Install Rust target
      shell: bash
      run: |
        rustup target add ${{ inputs.target }}
    - id: set_output
      name: Set output
      shell: bash
      run: |
        RUST_VERSION=$(rustc -V)
        echo "version=${RUST_VERSION}" >> $GITHUB_OUTPUT
