cli:
  - any:
      - changed-files:
          - any-glob-to-any-file: [ "cli/**/*" ]
lib:
  - any:
      - changed-files:
          - any-glob-to-any-file: [ "lib/**/*" ]
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: [ "Cargo.toml", "Cargo.lock", "**/Cargo.toml" ]
CI:
  - any:
      - changed-files:
          - any-glob-to-any-file: [ ".github/**/*.yml" ]
