services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    tty: true
    volumes:
      - .:/workspace
    working_dir: /workspace
    command: 'sleep infinity'
