[workspace]
members = ["cargo:cli"]

# Config for 'dist'
[dist]
allow-dirty = ["ci"]
# The preferred dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.28.0"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell", "powershell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = [
    "aarch64-apple-darwin",
    "aarch64-unknown-linux-gnu",
    # "aarch64-pc-windows-msvc",
    "x86_64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    # "x86_64-unknown-linux-musl",
    "x86_64-pc-windows-msvc",
]
# Which actions to run on pull requests
pr-run-mode = "upload"
# Whether to consider the binaries in a package for distribution (defaults true)
dist = true
# Where to host releases
hosting = "github"
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Whether to install an updater program
install-updater = true

precise-builds = true
features = ["acl", "memmap"]

[dist.github-custom-runners]
aarch64-unknown-linux-gnu = "ubuntu-22.04-arm"
x86_64-unknown-linux-gnu = "ubuntu-22.04"
# x86_64-unknown-linux-musl = "ubuntu-22.04"
# aarch64-pc-windows-msvc = "windows-11-arm"
x86_64-pc-windows-msvc = "windows-2022"

[dist.dependencies.apt]
libacl1-dev = { stage = ["build", "run"], targets = ["aarch64-unknown-linux-gnu", "x86_64-unknown-linux-gnu"] }
