package constants

var Header = []byte{
	0x89, // ¥x89
	0x50, // P
	0x4E, // N
	0x41, // A
	0x0D, // CR(Ctrl-M)
	0x0A, // LF(Ctrl-J)
	0x1A, // Ctrl-Z
	0x0A, // LF(Ctrl-J)
}

const MajorVersion uint8 = 0 // MajorVersion ...
const MinorVersion uint8 = 0 // MinorVersion ...

var NoCompression uint8 = 0      // NoCompression ...
var DeflateCompression uint8 = 1 // DeflateCompression ...
var ZstdCompression uint8 = 2    // ZstdCompression ...
var LzmaCompression uint8 = 4    // LzmaCompression ...

var NoEncryption uint8 = 0       // NoEncryption ...
var AesEncryption uint8 = 1      // AesEncryption ...
var CamelliaEncryption uint8 = 2 // CamelliaEncryption ...

var FileTypeNormal uint8 = 0    // FileTypeNormal ...
var FileTypeDirectory uint8 = 1 // FileTypeDirectory ...
var FileTypeSymlink uint8 = 2   // FileTypeSymlink ...
var FileTypeAlias uint8 = 4     // FileTypeAlias ...
