package constants

var Header = []byte{
	0x89, // ¥x89
	0x50, // P
	0x4E, // N
	0x41, // A
	0x0D, // CR(Ctrl-M)
	0x0A, // LF(Ctrl-J)
	0x1A, // Ctrl-Z
	0x0A, // LF(Ctrl-J)
}

const MajorVersion uint8 = 0 // MajorVersion ...
const MinorVersion uint8 = 0 // MinorVersion ...

type CompressionMethod uint8

const (
	NoCompression      CompressionMethod = 0 // NoCompression ...
	DeflateCompression CompressionMethod = 1 // DeflateCompression ...
	ZstdCompression    CompressionMethod = 2 // ZstdCompression ...
	LzmaCompression    CompressionMethod = 4 // LzmaCompression ...
)

type EncryptionMethod uint8

const (
	NoEncryption       EncryptionMethod = 0 // NoEncryption ...
	AesEncryption      EncryptionMethod = 1 // AesEncryption ...
	CamelliaEncryption EncryptionMethod = 2 // CamelliaEncryption ...
)

type FileType uint8

const (
	FileTypeNormal    FileType = 0 // FileTypeNormal ...
	FileTypeDirectory FileType = 1 // FileTypeDirectory ...
	FileTypeSymlink   FileType = 2 // FileTypeSymlink ...
	FileTypeAlias     FileType = 4 // FileTypeAlias ...
)
