mod edge_cases;
mod glob_pattern;
mod keep_solid;
mod missing_file;
mod multipart;
mod multiple_clauses;
mod numeric;
mod password;
mod password_file;
mod symbolic_all;
mod symbolic_combined;
mod symbolic_group;
mod symbolic_other;
mod symbolic_user;
mod unsolid;

use crate::utils::{EmbedExt, TestResources, archive, archive::FileEntryDef, setup};
use clap::Parser;
use pna::{
    Archive, DirEntryBuilder, EntryName, FileEntryBuilder, HardLinkEntryBuilder,
    SymlinkEntryBuilder,
};
use portable_network_archive::cli;
use std::fs::File;
use std::io::Write;

const ENTRY_PATH: &str = "test.txt";
const ENTRY_CONTENT: &[u8] = b"test content";

/// Precondition: An archive contains a file with permission 0o777 (rwxrwxrwx).
/// Action: Run `pna experimental chmod` with `-x` to remove execute permission for all.
/// Expectation: The archive entry's permission becomes 0o666 (rw-rw-rw-).
#[test]
fn archive_chmod() {
    setup();

    archive::create_archive_with_permissions(
        "chmod.pna",
        &[FileEntryDef {
            path: ENTRY_PATH,
            content: ENTRY_CONTENT,
            permission: 0o777,
        }],
    )
    .unwrap();

    cli::Cli::try_parse_from([
        "pna",
        "--quiet",
        "experimental",
        "chmod",
        "-f",
        "chmod.pna",
        "--",
        "-x",
        ENTRY_PATH,
    ])
    .unwrap()
    .execute()
    .unwrap();

    archive::for_each_entry("chmod.pna", |entry| {
        if entry.header().path() == ENTRY_PATH {
            let mode = entry
                .metadata()
                .permission_mode()
                .expect("entry should have permission mode metadata")
                .get();
            assert_eq!(mode & 0o777, 0o666, "-x on 0o777 should yield 0o666");
        }
    })
    .unwrap();
}

/// Precondition: An archive entry carries legacy fPRM metadata (no owner facets).
/// Action: Run `pna experimental chmod` to change its mode.
/// Expectation: The requested mode bit is cleared, the ownership rescued from fPRM
/// survives, and the stale fPRM chunk is removed.
#[test]
fn chmod_preserves_ownership_of_a_legacy_fprm_archive() {
    setup();
    TestResources::extract_in("0.33.0/zstd_keep_all.pna", "chmod_legacy_fprm/").unwrap();
    let archive = "chmod_legacy_fprm/0.33.0/zstd_keep_all.pna";

    cli::Cli::try_parse_from([
        "pna",
        "--quiet",
        "experimental",
        "chmod",
        "-f",
        archive,
        "u-w",
        "**",
    ])
    .unwrap()
    .execute()
    .unwrap();

    let mut seen = 0usize;
    archive::for_each_entry(archive, |entry| {
        seen += 1;
        let m = entry.metadata();
        assert_eq!(m.owner_uid().map(|v| v.get()), Some(0));
        assert_eq!(m.owner_user_name().map(|v| v.as_str()), Some("root"));
        assert_eq!(m.owner_group_name().map(|v| v.as_str()), Some("root"));
        let mode = m.permission_mode().expect("mode must survive").get();
        assert_eq!(
            mode & 0o200,
            0,
            "u-w must be cleared on {}",
            entry.header().path()
        );
    })
    .unwrap();
    assert_eq!(seen, 16, "fixture has 16 entries");
    let bytes = std::fs::read(archive).unwrap();
    assert!(
        !bytes.windows(4).any(|w| w == b"fPRM"),
        "legacy fPRM must be removed after chmod"
    );
}

/// Precondition: An archive entry has no permission metadata.
/// Action: Run `pna experimental chmod 600` on that entry.
/// Expectation: The requested mode is emitted as fMOd without generating legacy fPRM.
#[test]
fn archive_chmod_numeric_sets_missing_permission_mode() {
    setup();
    let path = "chmod_missing_mode_numeric.pna";
    {
        let mut archive = Archive::write_header(File::create(path).unwrap()).unwrap();
        let mut builder =
            FileEntryBuilder::new(EntryName::from_utf8_preserve_root(ENTRY_PATH)).unwrap();
        builder.write_all(ENTRY_CONTENT).unwrap();
        archive.add_entry(builder.build().unwrap()).unwrap();
        archive.finalize().unwrap();
    }

    cli::Cli::try_parse_from([
        "pna",
        "--quiet",
        "experimental",
        "chmod",
        "-f",
        path,
        "600",
        ENTRY_PATH,
    ])
    .unwrap()
    .execute()
    .unwrap();

    archive::for_each_entry(path, |entry| {
        assert_eq!(entry.metadata().permission_mode().unwrap().get(), 0o600);
    })
    .unwrap();
    let bytes = std::fs::read(path).unwrap();
    assert!(
        !bytes.windows(4).any(|w| w == b"fPRM"),
        "legacy fPRM must not be generated by chmod"
    );
}

/// Precondition: Archive entries of each supported kind have no permission metadata.
/// Action: Run symbolic `pna experimental chmod a-r` on all entries.
/// Expectation: Missing modes use default bases: directory 0755, all other
/// entry kinds 0644.
#[test]
fn archive_chmod_symbolic_uses_default_mode_for_missing_permission() {
    setup();
    let path = "chmod_missing_mode_symbolic.pna";
    {
        let mut archive = Archive::write_header(File::create(path).unwrap()).unwrap();

        let mut file = FileEntryBuilder::new("file.txt".into()).unwrap();
        file.write_all(b"file").unwrap();
        archive.add_entry(file.build().unwrap()).unwrap();

        archive
            .add_entry(DirEntryBuilder::new("dir".into()).build().unwrap())
            .unwrap();

        archive
            .add_entry(
                SymlinkEntryBuilder::new("link.txt".into(), "file.txt".into())
                    .unwrap()
                    .build()
                    .unwrap(),
            )
            .unwrap();

        archive
            .add_entry(
                HardLinkEntryBuilder::new("hard.txt".into(), "file.txt".into())
                    .unwrap()
                    .build()
                    .unwrap(),
            )
            .unwrap();

        archive.finalize().unwrap();
    }

    cli::Cli::try_parse_from([
        "pna",
        "--quiet",
        "experimental",
        "chmod",
        "-f",
        path,
        "a-r",
        "file.txt",
        "dir",
        "link.txt",
        "hard.txt",
    ])
    .unwrap()
    .execute()
    .unwrap();

    archive::for_each_entry(path, |entry| {
        let expected = match entry.header().path().as_str() {
            "dir" => 0o311,
            "file.txt" | "link.txt" | "hard.txt" => 0o200,
            other => panic!("unexpected entry: {other}"),
        };
        assert_eq!(
            entry.metadata().permission_mode().unwrap().get() & 0o777,
            expected
        );
    })
    .unwrap();
}
