name: format
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "lib/**"
      - "pna/**"
      - "cli/**"
      - "fuzz/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo/config.toml"
      - "rust-toolchain.toml"
      - ".github/workflows/format.yml"
  push:
    paths:
      - "lib/**"
      - "pna/**"
      - "cli/**"
      - "fuzz/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo/config.toml"
      - "rust-toolchain.toml"
      - ".github/workflows/format.yml"
permissions:
  contents: read # checkout
jobs:
  rust_check_format:
    name: Check format
    runs-on: ubuntu-slim
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: "rustfmt,rust-docs"
          cache: false
      - name: run check format
        run: cargo fmt --check
        env:
          RUST_BACKTRACE: 1
  rust_check_doc:
    name: Check documentation
    runs-on: ubuntu-slim
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
        with:
          components: "rustfmt,rust-docs"
          cache: false
      - name: run check doc
        run: cargo doc --no-deps -p libpna -p pna
        env:
          RUST_BACKTRACE: 1
          RUSTFLAGS: -Dwarnings
