name: format
on:
  workflow_dispatch:
  pull_request:
    paths:
      - "lib/**"
      - "pna/**"
      - "cli/**"
      - "fuzz/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo/config.toml"
      - "rust-toolchain.toml"
      - ".github/workflows/format.yml"
  push:
    paths:
      - "lib/**"
      - "pna/**"
      - "cli/**"
      - "fuzz/**"
      - "xtask/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - ".cargo/config.toml"
      - "rust-toolchain.toml"
      - ".github/workflows/format.yml"
permissions:
  contents: read # checkout
jobs:
  rust_check_format:
    name: Check format
    runs-on: ubuntu-slim
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
        with:
          components: "rustfmt,rust-docs"
          cache: false
      - name: run check format
        run: cargo fmt --check
        env:
          RUST_BACKTRACE: 1
  rust_check_doc:
    name: Check documentation
    runs-on: ubuntu-slim
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
        with:
          components: "rustfmt,rust-docs"
          cache: false
      - name: run check doc
        run: cargo doc --no-deps -p libpna -p pna
        env:
          RUST_BACKTRACE: 1
          RUSTFLAGS: -Dwarnings
