name: Labeler
on: [pull_request]

jobs:
  label:
    name: Label PR
    runs-on: ubuntu-slim
    timeout-minutes: 60
    permissions:
      contents: read # checkout
      issues: write # label issues
      pull-requests: write # label PRs
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/labeler@f27b608878404679385c85cfa523b85ccb86e213 # v6.1.0
      - uses: ./.github/actions/label_by_message
        with:
          pr_number: ${{ github.event.pull_request.number }}
          message_contains: ':boom:'
          label_name: 'break'
